--PATIENTREGSYS DataBase Creation

CREATE DATABASE PATIENTREGSYS

ON
(
	NAME = 'PRS_DATA',
	FILENAME = 'C:\PRSdatabase\PRS_DATA.MDF',
	SIZE = 4 MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1 MB
)

LOG ON
(
	 NAME='PRS_LOG',
	 FILENAME='C:\PRSdatabase\PRS_LOG.LDF'
)

--Login Table Creation

CREATE TABLE LOG_IN
(
	USERNAME VARCHAR(20) CONSTRAINT UNAME_NN NOT NULL,
	LOGIN_ID VARCHAR(20) CONSTRAINT LID_PK PRIMARY KEY,
	PASSWORD VARCHAR(20) CONSTRAINT PASS_NN NOT NULL,
	USER_ROLE VARCHAR(20) CONSTRAINT UR_NN NOT NULL,
)

DROP TABLE LOG_IN

--Insertion of default data into LOG_IN table

INSERT INTO LOG_IN VALUES('Barney Stinson','Barney01','admin123','Administrator') 
INSERT INTO LOG_IN VALUES('Lily Allen','Lily02','op12','Operator') 
INSERT INTO LOG_IN VALUES('Fred Flinstones','Fred43','freddie1','Doctor') 
INSERT INTO LOG_IN VALUES('Ray','Ray02','ray1','Doctor') 
INSERT INTO LOG_IN VALUES('Simon Cowell','Simon56','simon&&2','Doctor') 
INSERT INTO LOG_IN VALUES('Ted Mosby','tedmos23','col*#45','Administrator') 
INSERT INTO LOG_IN VALUES('Marsh Eric','marsh49','ericson','Operator') 
INSERT INTO LOG_IN VALUES('Sai Deepa','sai429','raviteja417','Operator') 


--Creation of DOCTOR_TABLE

CREATE TABLE DOCTOR_TABLE
(
	DOCTOR_NAME VARCHAR (50) CONSTRAINT DNAME_NN NOT NULL,
	DOCTOR_ID VARCHAR(10) CONSTRAINT DID_PK PRIMARY KEY,
	SPECIALIZATION VARCHAR(50) CONSTRAINT SPEC_NN NOT NULL,
	DEGREE VARCHAR(50) CONSTRAINT DEG_NN NOT NULL,
	CONTACT_NO VARCHAR(50) CONSTRAINT CN_NN NOT NULL
)

DROP TABLE DOCTOR_TABLE

--Default data of DOCTOR_TABLE

INSERT INTO DOCTOR_TABLE VALUES('Matt Raymond','Matt01','Neurologist','MBBS MS', '9873534253')
INSERT INTO DOCTOR_TABLE VALUES('Ray Romano','Ray02','Cardiologist','MBBS MS', '9563547578')
INSERT INTO DOCTOR_TABLE VALUES('Fred Flinstones','Fred43','Oncologist','MBBS MS', '8834523344')
INSERT INTO DOCTOR_TABLE VALUES('Simon Cowell','Simon56','Pediatrician','MBBS MS', '9489928363')
INSERT INTO DOCTOR_TABLE VALUES('Ted Mosbly','Tedmos23','General Physician','MBBS MS', '9344657782')
INSERT INTO DOCTOR_TABLE VALUES('Homer Son','Homer14','Pulmonologist','MBBS MS', '9494657782')
INSERT INTO DOCTOR_TABLE VALUES('Bart Simp','Bart78','Laser Specialist','MBBS MS', '5344657782')

--Creation of PATIENTS_MASTER

CREATE TABLE PATIENTS_MASTER
(
	PATIENT_ID INT CONSTRAINT PID_PK PRIMARY  KEY  IDENTITY(1001,1),
	FIRST_NAME VARCHAR(50) CONSTRAINT FNAME_NN NOT NULL,
	LAST_NAME VARCHAR(50) CONSTRAINT LNAME_NN NOT NULL,
	GENDER CHAR(10) CONSTRAINT GEN_D DEFAULT 'Male', 	
	AGE INT CONSTRAINT AGE_NN NOT NULL,
	CITY VARCHAR(50),
	STATE VARCHAR(50),
	PHONE_NO CHAR(10) CONSTRAINT PHONE_NN NOT NULL CONSTRAINT PHN_UK UNIQUE,
	EMAIL VARCHAR(100) CONSTRAINT EMAIL_UK UNIQUE CONSTRAINT PHONE_NN NOT NULL,
	DATE DATETIME CONSTRAINT DT_NN NOT NULL 
)


--Default data of DOCTOR_TABLE

INSERT INTO PATIENTS_MASTER VALUES( 'Kalpana', ' Chawla', 'Female',45, 'Ahmedabad', 'Gujarat', 9012345667, 'kalpana@shuttle.com', '7/2/2011')
INSERT INTO PATIENTS_MASTER VALUES( 'Sachin', ' Pilot', 'Male', 37, 'Lajpat Nagar', 'New Delhi', 8102345667, 'sachin@politics.com', '6/4/2011' )
INSERT INTO PATIENTS_MASTER VALUES( 'Kiran', ' Reddy', 'Male', 50, 'Hyderabad', 'Andhra Pradesh', 9200345667, 'kiran@chiefm.com', '2/5/2011' )
INSERT INTO PATIENTS_MASTER VALUES( 'Albert', 'Einstein', 'Male', 78, 'Banglore', 'Karnataka', 2003485667, 'albert@genius.com', '8/24/2011' )
INSERT INTO PATIENTS_MASTER VALUES( 'Marie', 'Curie', 'Female', 91, 'Mumbai', 'Maharashtra', 9003945667, 'marie@chem.com', '9/17/2011')
INSERT INTO PATIENTS_MASTER VALUES( 'Leonardo', 'DaVinci', 'Male', 61, 'Nagpur', 'Maharashtra', 7003945667, 'leo@art.com', '3/17/2011')
INSERT INTO PATIENTS_MASTER VALUES( 'Roger', 'Fed', 'Male', 30, 'Hyderabad', 'Andhra Pradesh', 5003945667, 'roger@tennis.com', '2/27/2011')

SELECT * FROM PATIENTS_MASTER
DROP TABLE PATIENTS_MASTER	
DELETE FROM PATIENTS_MASTER

--CREATION OF APPOINTMENT_TABLE

CREATE TABLE APPOINTMENT_TABLE
(
	PATIENT_ID INT CONSTRAINT PID_FK FOREIGN KEY REFERENCES PATIENTS_MASTER(PATIENT_ID) ON DELETE CASCADE,
	DOCTOR_ID VARCHAR(10) CONSTRAINT DID1_FK FOREIGN KEY REFERENCES DOCTOR_TABLE(DOCTOR_ID)ON DELETE CASCADE,
	SPECIALIZATION VARCHAR(50),REASON VARCHAR (MAX),
	APPOINTMENT_DATE_TIME SMALLDATETIME DEFAULT GETDATE() CONSTRAINT DATE_CK CHECK	
   (APPOINTMENT_DATE_TIME > GETDATE()),TIMESLOT VARCHAR(20) CONSTRAINT TS_NN NOT NULL
)
delete from APPOINTMENT_TABLE	
DROP TABLE APPOINTMENT_TABLE	
SELECT * FROM APPOINTMENT_TABLE

--DEFAULT VALUES OF APPOINTMENT_TABLE

INSERT INTO APPOINTMENT_TABLE VALUES(1001, 'Matt01', 'Neurologist', 'BREAKAGE OF NERVES', '8/12/2011', '10 :00AM--10:30AM')
INSERT INTO APPOINTMENT_TABLE VALUES( 1003,'Fred43', 'Oncologist', 'CHEMO CONSULTATION', '9/10/2011', '06:30PM--07:00PM')
INSERT INTO APPOINTMENT_TABLE VALUES(  1002,'Tedmos23', 'General Physician', 'COUGH & COLD', '7/3/2011', '11:30AM--12:00PM')
INSERT INTO APPOINTMENT_TABLE VALUES( 1005,'Simon56', 'Pediatrician',  'THROAT INFECTION', '5/8/2011', '06:00PM--06:30PM')
INSERT INTO APPOINTMENT_TABLE VALUES( 1004,'Ray02', 'Cardiologist', 'CHEST PAIN', '8/3/2011', '08:00PM--08:30PM')
INSERT INTO APPOINTMENT_TABLE VALUES( 1006,'Homer14', 'Pulmonologist', 'LUNGS PROBLEM', '10/17/2011', '06:00PM--08:30PM')
INSERT INTO APPOINTMENT_TABLE VALUES( 1007,'Bart78', 'Laser Specialist', 'Laser treatment', '12/27/2011', '11:00AM--11:30AM')

--WARD ACCOMODATION

CREATE TABLE ACCOMODATION  
(
WARD VARCHAR(50) CONSTRAINT W_NN NOT NULL,
PRICE MONEY CONSTRAINT P_NN NOT NULL
)

--DEFAULT VALUES OF ACCOMODATION

INSERT INTO ACCOMODATION VALUES ('ICU',6000)
INSERT INTO ACCOMODATION VALUES ('SPECIAL',3500)
INSERT INTO ACCOMODATION VALUES ('GENERAL',1500)

--TEST_DETAILS TABLE

CREATE TABLE TEST_DETAILS
(
TEST_ID INT CONSTRAINT TID_PK PRIMARY KEY CONSTRAINT TID_ID IDENTITY (201,1),
TEST_NAME VARCHAR(50)  CONSTRAINT TN_NN NOT NULL,
TEST_PRICE MONEY CONSTRAINT TP_NN NOT NULL
)

--DEFAULT VALUES OF TESTS

INSERT INTO TEST_DETAILS VALUES ('BLOOD TEST', '200')
INSERT INTO TEST_DETAILS VALUES ('X RAY', '300')
INSERT INTO TEST_DETAILS VALUES ('LIPID TEST', '500')
INSERT INTO TEST_DETAILS VALUES ('ECG', '400')
INSERT INTO TEST_DETAILS VALUES ('URINE SAMPLE', '100')

--STORED PROCEDURE FOR REGISTERING THE PATIENT

CREATE PROC USP_REGISTER_PATIENT
	@F_NAME VARCHAR(50),
	@L_NAME VARCHAR(50),
	@GENDR CHAR(10),
	@AGE1 INT,
	@CITY1 VARCHAR(50),
	@STATE1 VARCHAR(50),
	@PHNE CHAR(10),
	@EML VARCHAR(50),
	@DATE1 DATETIME
AS 
BEGIN
	SET @DATE1 = GETDATE();
	INSERT INTO PATIENTS_MASTER (FIRST_NAME, LAST_NAME, GENDER, AGE, CITY, STATE, PHONE_NO, EMAIL, DATE) VALUES( @F_NAME, @L_NAME, @GENDR, @AGE1, @CITY1, @STATE1, @PHNE, @EML, @DATE1) 
END

--VIEW FOR LOGIN & DOCTOR DETAILS

CREATE VIEW LOGIN_DOCDETAILS_VIEW
AS
SELECT LOGIN_ID, PASSWORD, DOCTOR_NAME, DOCTOR_ID, SPECIALIZATION, DEGREE, CONTACT_NO 
FROM LOG_IN LI INNER JOIN DOCTOR_TABLE DT 
ON LI.LOGIN_ID = DT.DOCTOR_ID										   
				
DELETE FROM PATIENTS_MASTER WHERE PATIENT_ID=1029
SELECT * FROM PATIENTS_MASTER
DELETE FROM APPOINTMENT_TABLE WHERE PATIENT_ID=1029

SELECT * FROM APPOINTMENT_TABLE
SELECT * FROM DOCTOR_TABLE
SELECT * FROM LOG_IN



SELECT dt.DOCTOR_NAME,dt.DOCTOR_ID,dt.SPECIALIZATION,dt.DEGREE,dt.CONTACT_NO,li.PASSWORD FROM DOCTOR_TABLE dt,LOG_IN li where li.USER_ROLE='DOCTOR'AND DT.DOCTOR_ID=LI.LOGIN_ID

select * from LOG_IN where USER_ROLE='DOCTOR'

CREATE TABLE BILLING_DETAILS
(
BILL_ID int IDENTITY(200,1) PRIMARY KEY,
PATIENT_ID INT CONSTRAINT FK_DET FOREIGN KEY REFERENCES PATIENTS_MASTER(PATIENT_ID) NOT NULL UNIQUE ,
TOTAL_BILL MONEY NOT NULL
)

insert into Billing_Details values(1001,15000)
insert into Billing_Details values(1002,25000)
insert into Billing_Details values(1003,35000)
insert into Billing_Details values(1004,45000)
insert into Billing_Details values(1005,55000)

SELECT * FROM BILLING_DETAILS
DROP TABLE BILLING_DETAILS
select * from PATIENTS_MASTER where PATIENT_ID=1037

DROP TABLE BILLING_DETAILS
DELETE FROM BILLING_DETAILS

SELECT * FROM DOCTOR_TABLE
SELECT * FROM LOG_IN

INSERT INTO APPOINTMENT_TABLE VALUES(1037, 'Matt01', 'Neurologist', 'BREAKAGE OF NERVES', '8/12/2011', '6:00AM--6:30AM')
INSERT INTO APPOINTMENT_TABLE VALUES(1037, 'Ray02', 'Cardiologist', 'Chest Pain', '4/21/2011', '6:00AM--6:30AM')
INSERT INTO APPOINTMENT_TABLE VALUES(1037, 'Ray02', 'Cardiologist', 'Chest Pain', '4/2/2011', '6:00AM--6:30AM')

SELECT * FROM DOCTOR_TABLE
SELECT * FROM LOG_IN

CREATE TRIGGER TRG
ON DOCTOR_TABLE
AFTER DELETE
AS
BEGIN
DELETE FROM LOG_IN
END
drop trigger trg
